INSERT INTO
    tech_skills_lookup (`name`)
VALUES ('Python'),
    ('JavaScript'),
    ('Java'),
    ('C#'),
    ('C++'),
    ('Swift'),
    ('Kotlin'),
    ('Ruby'),
    ('PHP'),
    ('TypeScript'),
    ('R'),
    ('React'),
    ('Angular'),
    ('Vue.js'),
    ('Node.js'),
    ('Django'),
    ('Flask'),
    ('Laravel'),
    ('Ruby on Rails'),
    ('ASP.NET'),
    ('SwiftUI'),
    ('UIKit'),
    ('Android Studio'),
    ('React Native'),
    ('Flutter'),
    ('Xamarin'),
    ('Ionic'),
    ('MySQL'),
    ('PostgreSQL'),
    ('MongoDB'),
    ('SQLite'),
    ('Oracle'),
    ('SQL Server'),
    ('Redis'),
    ('Cassandra'),
    ('AWS'),
    ('Azure'),
    ('Google Cloud Platform'),
    ('AWS Lambda'),
    ('Azure Functions'),
    ('Google Cloud Functions'),
    ('Terraform'),
    ('CloudFormation'),
    ('Docker'),
    ('Kubernetes'),
    ('Jenkins'),
    ('GitLab CI'),
    ('CircleCI'),
    ('Ansible'),
    ('Puppet'),
    ('Chef'),
    ('Nagios'),
    ('Prometheus'),
    ('Grafana'),
    ('TCP/IP'),
    ('DNS'),
    ('DHCP'),
    ('BGP'),
    ('OSPF'),
    ('Routers'),
    ('Switches'),
    ('Firewalls'),
    ('TensorFlow'),
    ('PyTorch'),
    ('Scikit-learn'),
    ('Keras'),
    ('Tableau'),
    ('Power BI'),
    ('Matplotlib'),
    ('Seaborn'),
    ('Apache Spark'),
    ('Wireshark'),
    ('Nmap'),
    ('Nessus'),
    ('Metasploit'),
    ('Kali Linux'),
    ('Snort'),
    ('Burp Suite'),
    ('OWASP ZAP'),
    ('Splunk'),
    ('Git'),
    ('GitHub'),
    ('Bitbucket'),
    ('Figma'),
    ('Sketch'),
    ('Adobe XD'),
    ('InVision'),
    ('SAP'),
    ('Salesforce'),
    ('HubSpot'),
    ('Microsoft Dynamics'),
    ('Oracle ERP'),
    ('Tableau'),
    ('Power BI'),
    ('VMware'),
    ('Hyper-V'),
    ('Apache Kafka'),
    ('ELK Stack'),
    ('Nginx'),
    ('Apache HTTP Server'),
    ('Go'),
    ('Perl'),
    ('Scala'),
    ('MATLAB'),
    ('Dart'),
    ('Spring Boot'),
    ('Express.js'),
    ('Svelte'),
    ('Next.js'),
    ('Nuxt.js'),
    ('Gatsby'),
    ('Quarkus'),
    ('Hadoop'),
    ('Spark Streaming'),
    ('Cypress'),
    ('JUnit'),
    ('TestNG'),
    ('Mocha'),
    ('Chai'),
    ('Jest'),
    ('Postman'),
    ('Appium'),
    ('Detox'),
    ('JMeter'),
    ('Travis CI'),
    ('Bamboo'),
    ('TeamCity'),
    ('Spinnaker'),
    ('Argo CD'),
    ('Vault'),
    ('Pulumi'),
    ('OpenShift'),
    ('Alibaba Cloud'),
    ('DigitalOcean'),
    ('IBM Cloud'),
    ('Cisco IOS'),
    ('Juniper Junos'),
    ('Nagios'),
    ('PRTG'),
    ('GraphQL'),
    ('WebSockets'),
    ('Blockchain'),
    ('Internet of Things (IoT)'),
    ('AR/VR Development'),
    ('Game Development'),
    ('Unity'),
    ('Unreal Engine');

INSERT INTO
    tech_skills_lookup (`name`)
VALUES ('Julia'),
    ('Haskell'),
    ('TypeScript'),
    ('CoffeeScript'),
    ('Shell Scripting'),
    ('Laravel'),
    ('Ruby on Rails'),
    ('Django'),
    ('Flask'),
    ('ASP.NET Core'),
    ('Meteor.js'),
    ('FastAPI'),
    ('Phoenix'),
    ('React Router'),
    ('Three.js'),
    ('Robot Framework'),
    ('Cucumber'),
    ('Gatling'),
    ('Locust'),
    ('Katalon Studio'),
    ('RestAssured'),
    ('GitLab CI/CD'),
    ('CircleCI'),
    ('Octopus Deploy'),
    ('Chef'),
    ('Puppet'),
    ('SaltStack'),
    ('Heroku'),
    ('Netlify'),
    ('Vercel'),
    ('IBM Watson'),
    ('AWS ECS'),
    ('AWS EKS'),
    ('Cloudflare'),
    ('Zabbix'),
    ('Mikrotik'),
    ('Cisco Meraki'),
    ('F5 Load Balancer'),
    ('Apache Airflow'),
    ('Apache Kafka'),
    ('Apache NiFi'),
    ('Talend'),
    ('Apache Flink'),
    ('Cassandra'),
    ('Elasticsearch'),
    ('Presto'),
    ('Hive'),
    ('Pig'),
    ('Computer Vision'),
    (
        'Natural Language Processing (NLP)'
    ),
    ('Quantum Computing'),
    ('Edge Computing'),
    ('Chatbot Development'),
    ('IoT Development'),
    ('Microservices Architecture'),
    ('Serverless Architecture'),
    ('Agile Methodologies'),
    ('Scrum'),
    ('Kanban'),
    ('Solidity'),
    ('Elixir'),
    ('F#'),
    ('Crystal'),
    ('Scheme'),
    ('NestJS'),
    ('Vuex'),
    ('Redux'),
    ('jQuery'),
    ('Backbone.js'),
    ('Foundation'),
    ('Bulma'),
    ('Selenium Grid'),
    ('Postman/Newman'),
    ('Katalon Recorder'),
    ('TestCafe'),
    ('Mockoon'),
    ('MockServer'),
    ('GitHub Actions'),
    ('Azure DevOps'),
    ('Bitbucket Pipelines'),
    ('Harness'),
    ('Codefresh'),
    ('AWS CloudFormation'),
    ('Google Cloud Functions'),
    ('Azure DevOps Services'),
    ('IBM Cloud Foundry'),
    ('Salesforce'),
    ('Netcat'),
    ('tcpdump'),
    ('OpenVPN'),
    ('Cisco Packet Tracer'),
    ('DataRobot'),
    ('H2O.ai'),
    ('Amazon Redshift Spectrum'),
    ('Apache Drill'),
    ('Kinesis'),
    ('Apache Kafka Streams'),
    ('Apache Superset'),
    ('Apache Druid'),
    ('KNIME'),
    ('RapidMiner'),
    ('Orange'),
    ('IBM Watson Studio'),
    ('Google AutoML'),
    ('Digital Marketing'),
    ('SEO'),
    ('Web Accessibility (a11y)'),
    ('User Research'),
    ('UX Writing'),
    (
        'Business Intelligence Tools (like QlikView)'
    ),
    ('Data Governance'),
    (
        'Data Privacy Regulations (GDPR, CCPA)'
    ),
    ('Disaster Recovery Planning'),
    ('Incident Response'),
    ('Rust'),
    ('Objective-C'),
    ('Ada'),
    ('Pascal'),
    ('Gatsby'),
    ('Nuxt.js'),
    ('Sapper'),
    ('Hugo'),
    ('Ember.js'),
    ('Laravel Nova'),
    ('Cypress.io'),
    ('Appium Studio'),
    ('RestSharp'),
    ('SoapUI Pro'),
    ('Playwright'),
    ('Spinnaker'),
    ('Jenkins X'),
    ('GitOps'),
    ('ArgoCD'),
    ('DigitalOcean'),
    ('Linode'),
    ('Heroku CI'),
    ('Cloud Foundry'),
    ('Cisco Prime'),
    ('Nagios XI'),
    ('Apache Pulsar'),
    ('Airflow'),
    ('dbt (data build tool)'),
    ('Looker'),
    ('Apache NiFi'),
    ('Cloudera'),
    ('MapR'),
    ('Apache Couchbase'),
    ('TensorBoard'),
    ('Hugging Face'),
    (
        'ONNX (Open Neural Network Exchange)'
    ),
    ('Change Management'),
    ('ITIL Framework'),
    ('Scrum Master Certification'),
    ('Data Migration Strategies'),
    ('Technical Documentation'),
    ('Open Source Contributions'),
    ('Social Media Management'),
    ('Agile Coaching'),
    (
        'MEAN Stack (MongoDB, Express.js, Angular, Node.js)'
    ),
    (
        'MERN Stack (MongoDB, Express.js, React, Node.js)'
    ),
    (
        'LAMP Stack (Linux, Apache, MySQL, PHP)'
    ),
    (
        'LEMP Stack (Linux, Nginx, MySQL, PHP)'
    ),
    (
        'Django Stack (Django, PostgreSQL, Python)'
    ),
    (
        'JAMstack (JavaScript, APIs, Markup)'
    ),
    (
        'Ruby on Rails Stack (Ruby, Rails, PostgreSQL)'
    ),
    (
        'Serverless Stack (AWS Lambda, API Gateway, DynamoDB)'
    ),
    (
        'Data Science Stack (Python, R, SQL, Jupyter)'
    ),
    ('Dart'),
    ('Racket'),
    ('Nim'),
    ('COBOL'),
    ('Smalltalk'),
    ('Flask-RESTful'),
    ('Spring Boot'),
    ('Quasar Framework'),
    ('Chakra UI'),
    ('Material-UI'),
    ('JUnit 5'),
    ('Robot Framework'),
    ('Gatling'),
    ('Gauge'),
    ('Octopus Deploy'),
    ('Wercker'),
    ('Drone CI'),
    ('Alibaba Cloud'),
    (
        'Oracle Cloud Infrastructure (OCI)'
    ),
    ('IBM Cloud Pak'),
    (
        'Kubernetes as a Service (KaaS)'
    ),
    (
        'SolarWinds Network Performance Monitor'
    ),
    ('OpenWrt'),
    ('Zabbix'),
    ('Talend Open Studio'),
    ('Apache Airflow'),
    (
        'Kettle (Pentaho Data Integration)'
    ),
    ('Apache Flink'),
    ('Apache Beam'),
    ('Presto'),
    ('Tidyverse'),
    ('Scikit-image'),
    ('Shiny'),
    ('Dataiku'),
    ('Change Management'),
    ('Vendor Management'),
    ('Supply Chain Management'),
    ('Remote Team Collaboration'),
    ('Digital Transformation'),
    (
        'Customer Experience Management (CEM)'
    );

DELETE FROM tech_skills_lookup
WHERE
    id IN (
        SELECT id
        FROM (
                SELECT id, ROW_NUMBER() OVER (
                        PARTITION BY
                            name
                        ORDER BY id
                    ) AS RN
                FROM tech_skills_lookup
            ) AS subquery
        WHERE
            RN > 1
    );